version: 2

# Required due to https://github.com/dependabot/dependabot-core/issues/6888
registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2

updates:
  - package-ecosystem: github-actions
    directory: /
    assignees: [takahirom]
    reviewers: [takahirom]
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday

  - package-ecosystem: gradle
    directory: "/"
    registries:
    - maven-google
    - gradle-plugin-portal
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday