version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    assignees: [takahirom]
    reviewers: [takahirom]
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
