name: Screenshot compare comment

on:
  workflow_run:
    workflows:
      - CompareScreenshot
    types:
      - completed

permissions: { }

run-name: ${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}

concurrency:
  group: compare-screenshot-workflow-hook-${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.name }}
  cancel-in-progress: true

jobs:
  after-CompareScreenshot:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    permissions:
      actions: read # for downloading artifacts
      contents: write # for writing screenshot on branch
      issues: none
      checks: none
      pull-requests: write # for creating a comment on pull requests

    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          name: pr
          run_id: ${{ github.event.workflow_run.id }}
      - id: get-pull-request-number
        name: Get pull request number
        shell: bash
        run: |
          echo "pull_request_number=$(cat NR)" >> $GITHUB_OUTPUT
      - id: check
        env:
          BRANCH_NAME: companion_${{ github.event.workflow_run.head_branch }}
        run:
          # orphan means it will create no history branch
          git checkout --orphan $BRANCH_NAME
      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: screenshot-diff
          path: diff-reports
      - id: generate-diff-reports
        name: Generate diff reports
        shell: bash
        run: |
          files=$(find . -type f -name "*_compare.png")
          
          # Create markdown table header
          echo "| Image |"
          echo "|-------|"
          
          # Iterate over the files and create table rows
          for file in $files; do
          echo "| ![]($file) |"
          done
          
          delimiter="$(openssl rand -hex 8)"
          echo "reports<<${delimiter}" >> $GITHUB_OUTPUT
          echo "$reports" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.get-pull-request-number.outputs.pull_request_number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
