name: Screenshot compare comment

on:
  workflow_run:
    workflows:
      - CompareScreenshot
    types:
      - completed

permissions: { }

run-name: ${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}

concurrency:
  group: compare-screenshot-workflow-hook-${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.name }}
  cancel-in-progress: true

jobs:
  after-CompareScreenshot:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    permissions:
      actions: read # for downloading artifacts
      contents: none
      issues: none
      checks: none
      pull-requests: write # for creating a comment on pull requests

    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          name: pr
          run_id: ${{ github.event.workflow_run.id }}
      - id: get-pull-request-number
        name: Get pull request number
        shell: bash
        run: |
          echo "pull_request_number=$(cat NR)" >> $GITHUB_OUTPUT
      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: screenshot-diff-test-results
          path: .diff-reports
      - id: generate-diff-reports
        name: Generate diff reports
        shell: bash
        run: |
          report_file=$(find .diff-reports -type f -name "compare-report.json")
          
          if [ -z "$report_file" ]; then
            echo "Error: compare-report.json not found in .diff-reports directory."
            exit 1
          fi
          
          total=$(jq '.summary.total' "$report_file")
          added=$(jq '.summary.added' "$report_file")
          changed=$(jq '.summary.changed' "$report_file")
          unchanged=$(jq '.summary.unchanged' "$report_file")
          
          if ! [[ $total =~ ^[0-9]+$ ]] || ! [[ $added =~ ^[0-9]+$ ]] || ! [[ $changed =~ ^[0-9]+$ ]] || ! [[ $unchanged =~ ^[0-9]+$ ]]; then
            echo "Error: Invalid data in ${report_file}. Please ensure the file contains valid numeric values for total, added, changed, and unchanged."
            exit 1
          fi
          
          reports=$(cat << EOF
          Summary of the Screenshot test Compare Report:
          
          Total: ${total}
          Added: ${added}
          Changed: ${changed}
          Unchanged: ${unchanged}
          EOF
          )
          
          delimiter="$(openssl rand -hex 8)"
          echo "reports<<${delimiter}" >> $GITHUB_OUTPUT
          echo "$reports" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.get-pull-request-number.outputs.pull_request_number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
